gestao_estoque/config/routes.rb
Rails.application.routes.draw do
  resources :movimentacoes, controller: 'movimentacoes'
  resources :movimentacaos, path: 'movimentacaos', controller: 'movimentacoes'
  resources :vendas
  resources :pedidos
  resources :estoques
  resources :historicos
  resources :fornecedores, controller: 'fornecedores'
  resources :fornecedors, path: 'fornecedores', controller: 'fornecedores'
  resources :clientes
  resources :funcionarios
  resources :produtos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "get#index"
  get '/index', to: 'get#index'
  get '/home', to: 'get#index'


end
# Método HTTP	     Caminho do URL        	Ação do Controlador
#   GET	           /fornecedores	        fornecedores#index
#   GET           	/fornecedores/new	    fornecedores#new
#   POST	          /fornecedores	         fornecedores#create
#   GET	           /fornecedores/:id	    fornecedores#show
#   GET          /fornecedores/:id/edit  	fornecedores#edit
#   PATCH/PUT      	/fornecedores/:id	    fornecedores#update
#   DELETE        	/fornecedores/:id	     fornecedores#destroy

gestao_estoque/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

gestao_estoque/app/models/cliente.rb
class Cliente < ApplicationRecord
end

gestao_estoque/app/models/estoque.rb
class Estoque < ApplicationRecord
  belongs_to :produto
end

gestao_estoque/app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
    self.table_name = 'fornecedores'  # Especifica o nome da tabela no plural
end

gestao_estoque/app/models/funcionario.rb
class Funcionario < ApplicationRecord
end

gestao_estoque/app/models/historico.rb
class Historico < ApplicationRecord
end

gestao_estoque/app/models/movimentacao.rb
class Movimentacao < ApplicationRecord
  self.table_name = 'movimentacoes'
  belongs_to :produto
end

gestao_estoque/app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :fornecedor
  belongs_to :produto
end

gestao_estoque/app/models/produto.rb
class Produto < ApplicationRecord
end

gestao_estoque/app/models/venda.rb
class Venda < ApplicationRecord
  belongs_to :cliente
  belongs_to :produto
end

gestao_estoque/app/controllers/get_controller.rb
class GetController < ApplicationController
  def index
    render template: 'index'
  end
end
  

gestao_estoque/app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: %i[ show edit update destroy ]

  # GET /pedidos or /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1 or /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos or /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to pedido_url(@pedido), notice: "Pedido was successfully created." }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1 or /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to pedido_url(@pedido), notice: "Pedido was successfully updated." }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1 or /pedidos/1.json
  def destroy
    @pedido.destroy!

    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: "Pedido was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_params
      params.require(:pedido).permit(:fornecedor_id, :produto_id, :quantidade, :data_pedido)
    end
end

gestao_estoque/app/controllers/vendas_controller.rb
class VendasController < ApplicationController
  before_action :set_venda, only: %i[ show edit update destroy ]

  # GET /vendas or /vendas.json
  def index
    @vendas = Venda.all
  end

  # GET /vendas/1 or /vendas/1.json
  def show
  end

  # GET /vendas/new
  def new
    @venda = Venda.new
  end

  # GET /vendas/1/edit
  def edit
  end

  # POST /vendas or /vendas.json
  def create
    @venda = Venda.new(venda_params)

    respond_to do |format|
      if @venda.save
        format.html { redirect_to venda_url(@venda), notice: "Venda was successfully created." }
        format.json { render :show, status: :created, location: @venda }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendas/1 or /vendas/1.json
  def update
    respond_to do |format|
      if @venda.update(venda_params)
        format.html { redirect_to venda_url(@venda), notice: "Venda was successfully updated." }
        format.json { render :show, status: :ok, location: @venda }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendas/1 or /vendas/1.json
  def destroy
    @venda.destroy!

    respond_to do |format|
      format.html { redirect_to vendas_url, notice: "Venda was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venda
      @venda = Venda.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def venda_params
      params.require(:venda).permit(:cliente_id, :produto_id, :quantidade, :data_venda)
    end
end

gestao_estoque/app/helpers/application_helper.rb
module ApplicationHelper
end

gestao_estoque/app/helpers/clientes_helper.rb
module ClientesHelper
end

gestao_estoque/app/helpers/estoques_helper.rb
module EstoquesHelper
end

gestao_estoque/app/helpers/fornecedores_helper.rb
module FornecedoresHelper
end

gestao_estoque/app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

gestao_estoque/app/helpers/historicos_helper.rb
module HistoricosHelper
end

gestao_estoque/app/helpers/movimentacoes_helper.rb
module MovimentacoesHelper
end

gestao_estoque/app/helpers/pedidos_helper.rb
module PedidosHelper
end

gestao_estoque/app/helpers/produtos_helper.rb
module ProdutosHelper
end

gestao_estoque/app/helpers/vendas_helper.rb
module VendasHelper
end

gestao_estoque/app/views/pedidos/_form.html.erb
<%= form_with(model: pedido) do |form| %>
  <% if pedido.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
        <% pedido.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :fornecedor_id, style: "display: block" %>
    <%= form.text_field :fornecedor_id %>
  </div>

  <div>
    <%= form.label :produto_id, style: "display: block" %>
    <%= form.text_field :produto_id %>
  </div>

  <div>
    <%= form.label :quantidade, style: "display: block" %>
    <%= form.number_field :quantidade %>
  </div>

  <div>
    <%= form.label :data_pedido, style: "display: block" %>
    <%= form.datetime_field :data_pedido %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

gestao_estoque/app/views/pedidos/_pedido.html.erb
<div id="<%= dom_id pedido %>">
  <p>
    <strong>Fornecedor:</strong>
    <%= pedido.fornecedor_id %>
  </p>

  <p>
    <strong>Produto:</strong>
    <%= pedido.produto_id %>
  </p>

  <p>
    <strong>Quantidade:</strong>
    <%= pedido.quantidade %>
  </p>

  <p>
    <strong>Data pedido:</strong>
    <%= pedido.data_pedido %>
  </p>

</div>

gestao_estoque/app/views/pedidos/edit.html.erb
<h1>Editing pedido</h1>

<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Show this pedido", @pedido %> |
  <%= link_to "Back to pedidos", pedidos_path %>
</div>

gestao_estoque/app/views/pedidos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pedidos</h1>

<div id="pedidos">
  <% @pedidos.each do |pedido| %>
    <%= render pedido %>
    <p>
      <%= link_to "Show this pedido", pedido %>
    </p>
  <% end %>
</div>

<%= link_to "New pedido", new_pedido_path %>

gestao_estoque/app/views/pedidos/new.html.erb
<h1>New pedido</h1>

<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Back to pedidos", pedidos_path %>
</div>

gestao_estoque/app/views/pedidos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pedido %>

<div>
  <%= link_to "Edit this pedido", edit_pedido_path(@pedido) %> |
  <%= link_to "Back to pedidos", pedidos_path %>

  <%= button_to "Destroy this pedido", @pedido, method: :delete %>
</div>

gestao_estoque/app/views/vendas/_form.html.erb
<%= form_with(model: venda) do |form| %>
  <% if venda.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(venda.errors.count, "error") %> prohibited this venda from being saved:</h2>

      <ul>
        <% venda.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cliente_id, style: "display: block" %>
    <%= form.text_field :cliente_id %>
  </div>

  <div>
    <%= form.label :produto_id, style: "display: block" %>
    <%= form.text_field :produto_id %>
  </div>

  <div>
    <%= form.label :quantidade, style: "display: block" %>
    <%= form.number_field :quantidade %>
  </div>

  <div>
    <%= form.label :data_venda, style: "display: block" %>
    <%= form.datetime_field :data_venda %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

gestao_estoque/app/views/vendas/_venda.html.erb
<div id="<%= dom_id venda %>">
  <p>
    <strong>Cliente:</strong>
    <%= venda.cliente_id %>
  </p>

  <p>
    <strong>Produto:</strong>
    <%= venda.produto_id %>
  </p>

  <p>
    <strong>Quantidade:</strong>
    <%= venda.quantidade %>
  </p>

  <p>
    <strong>Data venda:</strong>
    <%= venda.data_venda %>
  </p>

</div>

gestao_estoque/app/views/vendas/edit.html.erb
<h1>Editing venda</h1>

<%= render "form", venda: @venda %>

<br>

<div>
  <%= link_to "Show this venda", @venda %> |
  <%= link_to "Back to vendas", vendas_path %>
</div>

gestao_estoque/app/views/vendas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Vendas</h1>

<div id="vendas">
  <% @vendas.each do |venda| %>
    <%= render venda %>
    <p>
      <%= link_to "Show this venda", venda %>
    </p>
  <% end %>
</div>

<%= link_to "New venda", new_venda_path %>

gestao_estoque/app/views/vendas/new.html.erb
<h1>New venda</h1>

<%= render "form", venda: @venda %>

<br>

<div>
  <%= link_to "Back to vendas", vendas_path %>
</div>

gestao_estoque/app/views/vendas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @venda %>

<div>
  <%= link_to "Edit this venda", edit_venda_path(@venda) %> |
  <%= link_to "Back to vendas", vendas_path %>

  <%= button_to "Destroy this venda", @venda, method: :delete %>
</div>