gestao_estoque/config/routes.rb
Rails.application.routes.draw do
  resources :movimentacoes, controller: 'movimentacoes'
  resources :movimentacaos, path: 'movimentacaos', controller: 'movimentacoes'
  resources :vendas
  resources :pedidos
  resources :estoques
  resources :historicos
  resources :fornecedores, controller: 'fornecedores'
  resources :fornecedors, path: 'fornecedores', controller: 'fornecedores'
  resources :clientes
  resources :funcionarios
  resources :produtos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "get#index"
  get '/index', to: 'get#index'
  get '/home', to: 'get#index'


end
# Método HTTP	     Caminho do URL        	Ação do Controlador
#   GET	           /fornecedores	        fornecedores#index
#   GET           	/fornecedores/new	    fornecedores#new
#   POST	          /fornecedores	         fornecedores#create
#   GET	           /fornecedores/:id	    fornecedores#show
#   GET          /fornecedores/:id/edit  	fornecedores#edit
#   PATCH/PUT      	/fornecedores/:id	    fornecedores#update
#   DELETE        	/fornecedores/:id	     fornecedores#destroy

gestao_estoque/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

gestao_estoque/app/models/cliente.rb
class Cliente < ApplicationRecord
end

gestao_estoque/app/models/estoque.rb
class Estoque < ApplicationRecord
  belongs_to :produto
end

gestao_estoque/app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
    self.table_name = 'fornecedores'  # Especifica o nome da tabela no plural
end

gestao_estoque/app/models/funcionario.rb
class Funcionario < ApplicationRecord
end

gestao_estoque/app/models/historico.rb
class Historico < ApplicationRecord
end

gestao_estoque/app/models/movimentacao.rb
class Movimentacao < ApplicationRecord
  self.table_name = 'movimentacoes'
  belongs_to :produto
end

gestao_estoque/app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :fornecedor
  belongs_to :produto
end

gestao_estoque/app/models/produto.rb
class Produto < ApplicationRecord
end

gestao_estoque/app/models/venda.rb
class Venda < ApplicationRecord
  belongs_to :cliente
  belongs_to :produto
end

gestao_estoque/app/controllers/get_controller.rb
class GetController < ApplicationController
  def index
    render template: 'index'
  end
end
  

gestao_estoque/app/controllers/movimentacoes_controller.rb
class MovimentacoesController < ApplicationController
  before_action :set_movimentacao, only: %i[ show edit update destroy ]

  # GET /movimentacoes or /movimentacoes.json
  def index
    @movimentacoes = Movimentacao.all
  end

  # GET /movimentacoes/1 or /movimentacoes/1.json
  def show
  end

  # GET /movimentacoes/new
  def new
    @movimentacao = Movimentacao.new
  end

  # GET /movimentacoes/1/edit
  def edit
  end

  # POST /movimentacoes or /movimentacoes.json
  def create
    @movimentacao = Movimentacao.new(movimentacao_params)

    respond_to do |format|
      if @movimentacao.save
        format.html { redirect_to movimentacao_url(@movimentacao), notice: "Movimentacao was successfully created." }
        format.json { render :show, status: :created, location: @movimentacao }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movimentacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movimentacoes/1 or /movimentacoes/1.json
  def update
    respond_to do |format|
      if @movimentacao.update(movimentacao_params)
        format.html { redirect_to movimentacao_url(@movimentacao), notice: "Movimentacao was successfully updated." }
        format.json { render :show, status: :ok, location: @movimentacao }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movimentacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movimentacoes/1 or /movimentacoes/1.json
  def destroy
    @movimentacao.destroy!

    respond_to do |format|
      format.html { redirect_to movimentacoes_url, notice: "Movimentacao was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movimentacao
      @movimentacao = Movimentacao.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movimentacao_params
      params.require(:movimentacao).permit(:quantidade, :produto_id)
    end
end

gestao_estoque/app/helpers/application_helper.rb
module ApplicationHelper
end

gestao_estoque/app/helpers/clientes_helper.rb
module ClientesHelper
end

gestao_estoque/app/helpers/estoques_helper.rb
module EstoquesHelper
end

gestao_estoque/app/helpers/fornecedores_helper.rb
module FornecedoresHelper
end

gestao_estoque/app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

gestao_estoque/app/helpers/historicos_helper.rb
module HistoricosHelper
end

gestao_estoque/app/helpers/movimentacoes_helper.rb
module MovimentacoesHelper
end

gestao_estoque/app/helpers/pedidos_helper.rb
module PedidosHelper
end

gestao_estoque/app/helpers/produtos_helper.rb
module ProdutosHelper
end

gestao_estoque/app/helpers/vendas_helper.rb
module VendasHelper
end

gestao_estoque/app/views/movimentacoes/_form.html.erb
<%= form_with(model: movimentacao, url: movimentacoes_path) do |form| %>
  <% if movimentacao.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movimentacao.errors.count, "error") %> prohibited this movimentacao from being saved:</h2>

      <ul>
        <% movimentacao.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :quantidade, style: "display: block" %>
    <%= form.number_field :quantidade %>
  </div>

  <div>
    <%= form.label :produto_id, style: "display: block" %>
    <%= form.text_field :produto_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

gestao_estoque/app/views/movimentacoes/_movimentacao.html.erb
<div id="<%= dom_id movimentacao %>">
  <p>
    <strong>Quantidade:</strong>
    <%= movimentacao.quantidade %>
  </p>

  <p>
    <strong>Produto:</strong>
    <%= movimentacao.produto_id %>
  </p>

</div>

gestao_estoque/app/views/movimentacoes/edit.html.erb
<h1>Editing movimentacao</h1>

<%= render "form", movimentacao: @movimentacao %>

<br>

<div>
  <%= link_to "Show this movimentacao", @movimentacao %> |
  <%= link_to "Back to movimentacoes", movimentacoes_path %>
</div>

gestao_estoque/app/views/movimentacoes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Movimentações</h1>

<div id="movimentacoes">
  <% @movimentacoes.each do |movimentacao| %>
    <%# render movimentacao %>
    <%= render 'movimentacoes/movimentacao', movimentacao: movimentacao  %>

    <p>
      <%= link_to "Show this movimentacao", movimentacao %>
      <%#    = link_to "Show this movimentacao", movimentacao_path(movimentacao) %>
    </p>
  <% end %>
</div>

<%= link_to "New movimentacao", new_movimentacao_path %>

gestao_estoque/app/views/movimentacoes/new.html.erb
<h1>New movimentacao</h1>

<%= render "form", movimentacao: @movimentacao %>

<br>

<div>
  <%= link_to "Back to movimentacoes", movimentacoes_path %>
</div>

gestao_estoque/app/views/movimentacoes/show.html.erb
<p style="color: green"><%= notice %></p>

<%# render @movimentacao %>
<%= render 'movimentacoes/movimentacao', movimentacao: @movimentacao  %>


<div>
  <%= link_to "Edit this movimentacao", edit_movimentacao_path(@movimentacao) %> |
  <%= link_to "Back to movimentacoes", '/movimentacoes' %>

  <%= button_to "Destroy this movimentacao", @movimentacao, method: :delete %>
</div>