gestao_estoque/config/routes.rb
Rails.application.routes.draw do
  resources :movimentacoes, controller: 'movimentacoes'
  resources :movimentacaos, path: 'movimentacaos', controller: 'movimentacoes'
  resources :vendas
  resources :pedidos
  resources :estoques
  resources :historicos
  resources :fornecedores, controller: 'fornecedores'
  resources :fornecedors, path: 'fornecedores', controller: 'fornecedores'
  resources :clientes
  resources :funcionarios
  resources :produtos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "get#index"
  get '/index', to: 'get#index'
  get '/home', to: 'get#index'


end
# Método HTTP	     Caminho do URL        	Ação do Controlador
#   GET	           /fornecedores	        fornecedores#index
#   GET           	/fornecedores/new	    fornecedores#new
#   POST	          /fornecedores	         fornecedores#create
#   GET	           /fornecedores/:id	    fornecedores#show
#   GET          /fornecedores/:id/edit  	fornecedores#edit
#   PATCH/PUT      	/fornecedores/:id	    fornecedores#update
#   DELETE        	/fornecedores/:id	     fornecedores#destroy

gestao_estoque/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

gestao_estoque/app/models/cliente.rb
class Cliente < ApplicationRecord
end

gestao_estoque/app/models/estoque.rb
class Estoque < ApplicationRecord
  belongs_to :produto
end

gestao_estoque/app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
    self.table_name = 'fornecedores'  # Especifica o nome da tabela no plural
end

gestao_estoque/app/models/funcionario.rb
class Funcionario < ApplicationRecord
end

gestao_estoque/app/models/historico.rb
class Historico < ApplicationRecord
end

gestao_estoque/app/models/movimentacao.rb
class Movimentacao < ApplicationRecord
  self.table_name = 'movimentacoes'
  belongs_to :produto
end

gestao_estoque/app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :fornecedor
  belongs_to :produto
end

gestao_estoque/app/models/produto.rb
class Produto < ApplicationRecord
end

gestao_estoque/app/models/venda.rb
class Venda < ApplicationRecord
  belongs_to :cliente
  belongs_to :produto
end

gestao_estoque/app/controllers/fornecedores_controller.rb
class FornecedoresController < ApplicationController
  before_action :set_fornecedor, only: %i[ show edit update destroy ]

  # GET /fornecedores or /fornecedores.json
  def index
    @fornecedores = Fornecedor.all
  end

  # GET /fornecedores/1 or /fornecedores/1.json
  def show
  end

  # GET /fornecedores/new
  def new
    @fornecedor = Fornecedor.new
  end

  # GET /fornecedores/1/edit
  def edit
  end

  # POST /fornecedores or /fornecedores.json
  def create
    @fornecedor = Fornecedor.new(fornecedor_params)

    respond_to do |format|
      if @fornecedor.save
        format.html { redirect_to fornecedor_url(@fornecedor), notice: "Fornecedor was successfully created." }
        format.json { render :show, status: :created, location: @fornecedor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fornecedores/1 or /fornecedores/1.json
  def update
    respond_to do |format|
      if @fornecedor.update(fornecedor_params)
        format.html { redirect_to fornecedor_url(@fornecedor), notice: "Fornecedor was successfully updated." }
        format.json { render :show, status: :ok, location: @fornecedor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedores/1 or /fornecedores/1.json
  def destroy
    @fornecedor.destroy!

    respond_to do |format|
      format.html { redirect_to fornecedores_url, notice: "Fornecedor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fornecedor
      @fornecedor = Fornecedor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fornecedor_params
      params.require(:fornecedor).permit(:nome, :contato)
    end
end

gestao_estoque/app/controllers/get_controller.rb
class GetController < ApplicationController
  def index
    render template: 'index'
  end
end
  

gestao_estoque/app/helpers/application_helper.rb
module ApplicationHelper
end

gestao_estoque/app/helpers/clientes_helper.rb
module ClientesHelper
end

gestao_estoque/app/helpers/estoques_helper.rb
module EstoquesHelper
end

gestao_estoque/app/helpers/fornecedores_helper.rb
module FornecedoresHelper
end

gestao_estoque/app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

gestao_estoque/app/helpers/historicos_helper.rb
module HistoricosHelper
end

gestao_estoque/app/helpers/movimentacoes_helper.rb
module MovimentacoesHelper
end

gestao_estoque/app/helpers/pedidos_helper.rb
module PedidosHelper
end

gestao_estoque/app/helpers/produtos_helper.rb
module ProdutosHelper
end

gestao_estoque/app/helpers/vendas_helper.rb
module VendasHelper
end

gestao_estoque/app/views/fornecedores/_form.html.erb
<%= form_with(model: fornecedor) do |form| %>
  <% if fornecedor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fornecedor.errors.count, "error") %> prohibited this fornecedor from being saved:</h2>

      <ul>
        <% fornecedor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :contato, style: "display: block" %>
    <%= form.text_field :contato %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

gestao_estoque/app/views/fornecedores/_fornecedor.html.erb
<div id="<%= dom_id fornecedor %>">
  <p>
    <strong>Nome:</strong>
    <%= fornecedor.nome %>
  </p>

  <p>
    <strong>Contato:</strong>
    <%= fornecedor.contato %>
  </p>

</div>

gestao_estoque/app/views/fornecedores/edit.html.erb
<h1>Editing fornecedor</h1>

<%= render "form", fornecedor: @fornecedor %>

<br>

<div>
  <%= link_to "Show this fornecedor", @fornecedor %> |
  <%= link_to "Back to fornecedores", fornecedores_path %>
</div>

gestao_estoque/app/views/fornecedores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Fornecedores</h1>

<div id="fornecedores">
  <% @fornecedores.each do |fornecedor| %>
    <%= render 'fornecedores/fornecedor', fornecedor: fornecedor  %>
    <p>
      <%= link_to "Show this fornecedor", fornecedor %>
      <%# link_to "Show this fornecedor", fornecedor_path(fornecedor) %>
    </p>
  <% end %>
</div>

<%= link_to "New fornecedor", new_fornecedor_path %>

gestao_estoque/app/views/fornecedores/new.html.erb
<h1>New fornecedor</h1>

<%= render "form", fornecedor: @fornecedor %>

<br>

<div>
  <%= link_to "Back to fornecedores", fornecedores_path %>
</div>

gestao_estoque/app/views/fornecedores/show.html.erb
<p style="color: green"><%= notice %></p>

<%# render @fornecedor %>
<%= render 'fornecedores/fornecedor', fornecedor: @fornecedor  %>


<div>
  <%= link_to "Edit this fornecedor", edit_fornecedor_path(@fornecedor) %> |
  <%= link_to "Back to fornecedores", fornecedores_path %>

  <%= button_to "Destroy this fornecedor", @fornecedor, method: :delete %>
</div>