gestao_estoque/config/routes.rb
Rails.application.routes.draw do
  resources :movimentacoes, controller: 'movimentacoes'
  resources :movimentacaos, path: 'movimentacaos', controller: 'movimentacoes'
  resources :vendas
  resources :pedidos
  resources :estoques
  resources :historicos
  resources :fornecedores, controller: 'fornecedores'
  resources :fornecedors, path: 'fornecedores', controller: 'fornecedores'
  resources :clientes
  resources :funcionarios
  resources :produtos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "get#index"
  get '/index', to: 'get#index'
  get '/home', to: 'get#index'


end
# Método HTTP	     Caminho do URL        	Ação do Controlador
#   GET	           /fornecedores	        fornecedores#index
#   GET           	/fornecedores/new	    fornecedores#new
#   POST	          /fornecedores	         fornecedores#create
#   GET	           /fornecedores/:id	    fornecedores#show
#   GET          /fornecedores/:id/edit  	fornecedores#edit
#   PATCH/PUT      	/fornecedores/:id	    fornecedores#update
#   DELETE        	/fornecedores/:id	     fornecedores#destroy

gestao_estoque/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

gestao_estoque/app/models/cliente.rb
class Cliente < ApplicationRecord
end

gestao_estoque/app/models/estoque.rb
class Estoque < ApplicationRecord
  belongs_to :produto
end

gestao_estoque/app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
    self.table_name = 'fornecedores'  # Especifica o nome da tabela no plural
end

gestao_estoque/app/models/funcionario.rb
class Funcionario < ApplicationRecord
end

gestao_estoque/app/models/historico.rb
class Historico < ApplicationRecord
end

gestao_estoque/app/models/movimentacao.rb
class Movimentacao < ApplicationRecord
  self.table_name = 'movimentacoes'
  belongs_to :produto
end

gestao_estoque/app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :fornecedor
  belongs_to :produto
end

gestao_estoque/app/models/produto.rb
class Produto < ApplicationRecord
end

gestao_estoque/app/models/venda.rb
class Venda < ApplicationRecord
  belongs_to :cliente
  belongs_to :produto
end

gestao_estoque/app/controllers/get_controller.rb
class GetController < ApplicationController
  def index
    render template: 'index'
  end
end
  

gestao_estoque/app/helpers/application_helper.rb
module ApplicationHelper
end

gestao_estoque/app/helpers/clientes_helper.rb
module ClientesHelper
end

gestao_estoque/app/helpers/estoques_helper.rb
module EstoquesHelper
end

gestao_estoque/app/helpers/fornecedores_helper.rb
module FornecedoresHelper
end

gestao_estoque/app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

gestao_estoque/app/helpers/historicos_helper.rb
module HistoricosHelper
end

gestao_estoque/app/helpers/pedidos_helper.rb
module PedidosHelper
end

gestao_estoque/app/helpers/produtos_helper.rb
module ProdutosHelper
end

gestao_estoque/app/helpers/vendas_helper.rb
module VendasHelper
end

gestao_estoque/app/views/shared/_footer.html.erb
<!-- _footer.html.erb -->

<footer>
  <div>
    <p>&copy; <%= Time.now.year %> Gestor de Estoque. Todos os direitos reservados.</p>
  </div>
</footer>

gestao_estoque/app/views/shared/_header.html.erb
<!-- _header.html.erb -->


<section>
  <a href="/">Gestor de Estoque</a>
  <button id="toggleButton" class="botao" onclick="toggleMenu()"> &equiv; </button>
  <nav id="navMenu" class="menu">
    <div>
      <ul class="menu-horizontal" style="list-style-type: none">
        <li >
          <%= link_to 'Produtos', produtos_path %>
        </li>
        <li>
          <%= link_to 'Funcionários', funcionarios_path %>
        </li>
        <li>
          <%= link_to 'Clientes', clientes_path %>
        </li>
        <li>
          <%= link_to 'Fornecedores', fornecedores_path %>
        </li>
        <li>
          <%= link_to 'Estoques', estoques_path %>
        </li>
        <li>
          <%= link_to 'Pedidos', pedidos_path %>
        </li>
        <li>
          <%= link_to 'Vendas', vendas_path %>
        </li>
        <li>
          <%= link_to 'Movimentação', '/movimentacoes' %>
        </li>
        <li>
          <%= link_to 'Histórico', historicos_path %>
        </li>
      </ul>
    </div>
  </nav>
</section>


<style>
/* Estilo para o botão */
.botao {
  border: none; /* Sem borda */
  padding: 15px 32px; /* Espaçamento interno */
  text-align: center; /* Alinhamento do texto */
  text-decoration: none; /* Sem decoração de texto */
  display: inline-block; /* Exibição em bloco */
  font-size: 16px; /* Tamanho da fonte */
  margin: 4px 2px; /* Margem */
  cursor: pointer; /* Cursor do mouse */
  list-style-type: none;/* Cursor do mouse */
}

/* Estilo para o menu de navegação */
.menu {
  display: none; /* Ocultar o menu por padrão */
}

.menu-horizontal {
  display: flex; /* Transforma os itens em flex items */
  justify-content: space-between; /* Espaço igual entre os itens */
  align-items: center; /* Centraliza verticalmente os itens */
  font-size: 14px; /* Tamanho da letra */
}

</style>

<!-- Script para mostrar/ocultar o menu -->
<script>
  function toggleMenu() {
    var menu = document.querySelector('.menu');
    if (menu.style.display === 'none') {
        menu.style.display = 'block';
    } else {
        menu.style.display = 'none';
    }
  }
</script>